"""
Django settings for izone project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR,'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xt*v2appmo7@6nfge=bzw46$xm4flag-i1+83%!3bc)7&1&6nz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.redirects',

    'django_python3_ldap',
    'haystack',
    'users',
    'Precord',
    'comment',
    'T_map',
    'DjangoUeditor',
    'InstallRTOS',
]
AUTH_USER_MODEL='users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'izone.middleware.CustomAuthMiddleware',
]

ROOT_URLCONF = 'izone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'izone.context_processor.settings',
                'izone.context_processor.ip_address',
            ],
        },
    },
]

WSGI_APPLICATION = 'izone.wsgi.application'

AUTHENTICATION_BACKENDS = (
    "django_python3_ldap.auth.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)
LDAP_AUTH_URL = "china.huawei.com"
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "DC=china,DC=huawei,DC=com"
LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"
LDAP_AUTH_USER_FIELDS = {
    "job_number":"username",
#    "last_name":"username",
#    "first_name":"username",
#    "email":"mail"
}
#LDAP_AUTH_USER_FIELDS = {
#    "username": "uid",
#    "first_name": "givenName",
#    "last_name": "sn",
#    "email": "mail",
#}
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"
LDAP_AUTH_USER_LOOKUP_FIELDS = ("job_number",)

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'izone',
        'USER': 'root',
        'PASSWORD':'root',  
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS=False
EMAIL_HOST='smtpscn.huawei.com'
EMAIL_HOST_USER='cwx331849'
EMAIL_HOST_PASSWORD='@wsx123456'
DEFAULT_FROM_EMAIL='caotao<caotao4@huawei.com>'


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR,"commono_static"),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
#MEDIA_URL = 'http://10.251.195.192:8888/admin/books/date_time/add/'

BASE_PAGE_BY = 10
BASE_ORPHANS = 5
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE':'Precord.whoosh_cn_backend.WhooshEngine',  # 靠靠靠靠靠靠靠靠?        'PATH':os.path.join(BASE_DIR,'whoosh_index'),  #靠靠靠靠靠靠靠靠靠靠靠靠? 
    }
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
CACHES={
  'default':{
    'BACKEND':'django_redis.cache.RedisCache',
    'LOCATION':'redis://127.0.0.1:6379/1',
    'TIMEOUT':600,
    'OPTIONS':{
      'CLIENT_CLASS':"django_redis.client.DefaultClient",
      'MAX_ENTRIES':2000,
    }
  }
}
SEND_TO = [
    "libin10@huawei.com",
    "tangyifeng@huawei.com",
]
#LOGGING={
# error
#  'version':1,
#  'disable_existing_loggers':False,
#  'handlers':{
#    'console':{
#      'class':'logging.StreamHandler',
#    },
#  },
#  'loggers':{
#    'django.db.backends':{
#      'handlers':['console'],
#      'level':'DEBUG' if DEBUG else 'INFO',
#    },
#  },
#}
